### ISSUE TITLE
Could not log "sql.active_record" event. ArgumentError: wrong number of arguments (given 1, expected 0)

### ISSUE THREAD

**Issue by ItaloCobains** [socketry/console-adapter-rails#12]
Hello, everyone.

I updated my project using `rails 6` to `rails 7`, switch `puma` to `falcon` and add the gem `console-adapter-rails` in the project to have logs again. It looked good until now, i've this error with so much frequency in my queries. 

```
 1m    error: Rails: Reading HTTP/1.1 requests for Async::HTTP::Protocol::HTTP1::Server. [ec=0x52f8] [pid=92] [2024-11-27 13:37:31 +0000]
               | Could not log "sql.active_record" event. ArgumentError: wrong number of arguments (given 1, expected 0) ["/usr/local/bundle/gems/activerecord-7.1.4.2/lib/active_record/connection_adapters/abstract/query_cache.rb:175:in `block in cache_notification_info'", "/usr/local/bundle/gems/console-adapter-rails-0.4.1/lib/console/adapter/rails/active_record.rb:51:in `block in update_binds'", "/usr/local/bundle/gems/console-adapter-rails-0.4.1/lib/console/adapter/rails/active_record.rb:50:in `map'", "/usr/local/bundle/gems/console-adapter-rails-0.4.1/lib/console/adapter/rails/active_record.rb:50:in `with_index'", "/usr/local/bundle/gems/console-adapter-rails-0.4.1/lib/console/adapter/rails/active_record.rb:50:in `update_binds'", "/usr/local/bundle/gems/console-adapter-rails-0.4.1/lib/console/adapter/rails/active_record.rb:35:in `sql'", "/usr/local/bundle/gems/activesupport-7.1.4.2/lib/active_support/subscriber.rb:137:in `call'", "/usr/local/bundle/gems/activesupport-7.1.4.2/lib/active_support/log_subscriber.rb:151:in `call'", "/usr/local/bundle/gems/activesupport-7.1.4.2/lib/active_support/notifications/fanout.rb:181:in `block in finish'", "/usr/local/bundle/gems/activesupport-7.1.4.2/lib/active_support/notifications/fanout.rb:26:in `block in iterate_guarding_exceptions'", "/usr/local/bundle/gems/activesupport-7.1.4.2/lib/active_support/notifications/fanout.rb:25:in `each'", "/usr/local/bundle/gems/activesupport-7.1.4.2/lib/active_support/notifications/fanout.rb:25:in `iterate_guarding_exceptions'", "/usr/local/bundle/gems/activesupport-7.1.4.2/lib/active_support/notifications/fanout.rb:125:in `each'", "/usr/local/bundle/gems/activesupport-7.1.4.2/lib/active_support/notifications/fanout.rb:180:in `finish'", "/usr/local/bundle/gems/activesupport-7.1.4.2/lib/active_support/notifications/fanout.rb:262:in `block in finish_with_values'", "/usr/local/bundle/gems/activesupport-7.1.4.2/lib/active_support/notifications/fanout.rb:26:in `block in iterate_guarding_exceptions'", "/usr/local/bundle/gems/activesupport-7.1.4.2/lib/active_support/notifications/fanout.rb:25:in `each'", "/usr/local/bundle/gems/activesupport-7.1.4.2/lib/active_support/notifications/fanout.rb:25:in `iterate_guarding_exceptions'", "/usr/local/bundle/gems/activesupport-7.1.4.2/lib/active_support/notifications/fanout.rb:261:in `finish_with_values'", "/usr/local/bundle/gems/activesupport-7.1.4.2/lib/active_support/notifications/fanout.rb:254:in `finish'", "/usr/local/bundle/gems/activesupport-7.1.4.2/lib/active_support/notifications/instrumenter.rb:64:in `instrument'", "/usr/local/bundle/gems/activesupport-7.1.4.2/lib/active_support/notifications.rb:206:in `instrument'", "/usr/local/bundle/gems/activerecord-7.1.4.2/lib/active_record/connection_adapters/abstract/query_cache.rb:160:in `cache_sql'", "/usr/local/bundle/gems/activerecord-7.1.4.2/lib/active_record/connection_adapters/abstract/query_cache.rb:112:in `select_all'", "/usr/local/bundle/gems/activerecord-7.1.4.2/lib/active_record/querying.rb:62:in `_query_by_sql'", "/usr/local/bundle/gems/activerecord-7.1.4.2/lib/active_record/querying.rb:51:in `find_by_sql'", "/usr/local/bundle/gems/bullet-7.2.0/lib/bullet/active_record71.rb:19:in `find_by_sql'", "/usr/local/bundle/gems/activerecord-7.1.4.2/lib/active_record/statement_cache.rb:150:in `execute'", "/usr/local/bundle/gems/activerecord-7.1.4.2/lib/active_record/core.rb:431:in `cached_find_by'", "/usr/local/bundle/gems/activerecord-7.1.4.2/lib/active_record/core.rb:300:in `find_by'", "/usr/local/bundle/gems/devise_token_auth-1.2.3/app/models/devise_token_auth/concerns/active_record_support.rb:15:in `dta_find_by'", "/usr/local/bundle/gems/devise_token_auth-1.2.3/app/controllers/devise_token_auth/concerns/set_user_by_token.rb:84:in `set_user_by_token'", "/usr/local/bundle/gems/devise_token_auth-1.2.3/lib/devise_token_auth/controllers/helpers.rb:130:in `current_user'", "/app/app/controllers/application_controller.rb:30:in `append_info_to_payload'", "/usr/local/bundle/gems/actionpack-7.1.4.2/lib/action_controller/metal/instrumentation.rb:82:in `block in process_action'", "/usr/local/bundle/gems/activesupport-7.1.4.2/lib/active_support/notifications.rb:206:in `block in instrument'", "/usr/local/bundle/gems/activesupport-7.1.4.2/lib/active_support/notifications/instrumenter.rb:58:in `instrument'", "/usr/local/bundle/gems/activesupport-7.1.4.2/lib/active_support/notifications.rb:206:in `instrument'", "/usr/local/bundle/gems/actionpack-7.1.4.2/lib/action_controller/metal/instrumentation.rb:73:in `process_action'", "/usr/local/bundle/gems/actionpack-7.1.4.2/lib/action_controller/metal/params_wrapper.rb:261:in `process_action'", "/usr/local/bundle/gems/activerecord-7.1.4.2/lib/active_record/railties/controller_runtime.rb:32:in `process_action'", "/usr/local/bundle/gems/actionpack-7.1.4.2/lib/abstract_controller/base.rb:160:in `process'", "/usr/local/bundle/gems/actionview-7.1.4.2/lib/action_view/rendering.rb:40:in `process'", "/usr/local/bundle/gems/actionpack-7.1.4.2/lib/action_controller/metal.rb:227:in `dispatch'", "/usr/local/bundle/gems/actionpack-7.1.4.2/lib/action_controller/metal.rb:309:in `dispatch'", "/usr/local/bundle/gems/actionpack-7.1.4.2/lib/action_dispatch/routing/route_set.rb:49:in `dispatch'", "/usr/local/bundle/gems/actionpack-7.1.4.2/lib/action_dispatch/routing/route_set.rb:32:in `serve'", "/usr/local/bundle/gems/actionpack-7.1.4.2/lib/action_dispatch/journey/router.rb:51:in `block in serve'", "/usr/local/bundle/gems/actionpack-7.1.4.2/lib/action_dispatch/journey/router.rb:131:in `block in find_routes'", "/usr/local/bundle/gems/actionpack-7.1.4.2/lib/action_dispatch/journey/router.rb:124:in `each'", "/usr/local/bundle/gems/actionpack-7.1.4.2/lib/action_dispatch/journey/router.rb:124:in `find_routes'", "/usr/local/bundle/gems/actionpack-7.1.4.2/lib/action_dispatch/journey/router.rb:32:in `serve'", "/usr/local/bundle/gems/actionpack-7.1.4.2/lib/action_dispatch/routing/route_set.rb:882:in `call'", "/usr/local/bundle/gems/omniauth-2.1.2/lib/omniauth/strategy.rb:470:in `call_app!'", "/usr/local/bundle/gems/omniauth_openid_connect-0.6.1/lib/omniauth/strategies/openid_connect.rb:155:in `other_phase'", "/usr/local/bundle/gems/omniauth-2.1.2/lib/omniauth/strategy.rb:195:in `call!'", "/usr/local/bundle/gems/omniauth-2.1.2/lib/omniauth/strategy.rb:169:in `call'", "/usr/local/bundle/gems/omniauth-2.1.2/lib/omniauth/strategy.rb:202:in `call!'", "/usr/local/bundle/gems/omniauth-2.1.2/lib/omniauth/strategy.rb:169:in `call'", "/usr/local/bundle/gems/omniauth-2.1.2/lib/omniauth/strategy.rb:202:in `call!'", "/usr/local/bundle/gems/omniauth-2.1.2/lib/omniauth/strategy.rb:169:in `call'", "/usr/local/bundle/gems/omniauth-2.1.2/lib/omniauth/builder.rb:44:in `call'", "/usr/local/bundle/gems/bullet-7.2.0/lib/bullet/rack.rb:17:in `call'", "/usr/local/bundle/gems/rack-robustness-1.2.0/lib/rack/robustness.rb:104:in `call!'", "/usr/local/bundle/gems/rack-robustness-1.2.0/lib/rack/robustness.rb:95:in `call'", "/usr/local/bundle/gems/rack-2.2.10/lib/rack/session/abstract/id.rb:266:in `context'", "/usr/local/bundle/gems/rack-2.2.10/lib/rack/session/abstract/id.rb:260:in `call'", "/usr/local/bundle/gems/actionpack-7.1.4.2/lib/action_dispatch/middleware/cookies.rb:689:in `call'", "/usr/local/bundle/gems/warden-1.2.9/lib/warden/manager.rb:36:in `block in call'", "/usr/local/bundle/gems/warden-1.2.9/lib/warden/manager.rb:34:in `catch'", "/usr/local/bundle/gems/warden-1.2.9/lib/warden/manager.rb:34:in `call'", "/usr/local/bundle/gems/ros-apartment-3.1.0/lib/apartment/elevators/generic.rb:22:in `block in call'", "/usr/local/bundle/gems/ros-apartment-3.1.0/lib/apartment/adapters/abstract_adapter.rb:89:in `switch'", "/usr/local/lib/ruby/3.2.0/forwardable.rb:240:in `switch'", "/usr/local/bundle/gems/ros-apartment-3.1.0/lib/apartment/elevators/generic.rb:22:in `call'", "/app/lib/subdomain_with_404.rb:4:in `call'", "/usr/local/bundle/gems/rack-2.2.10/lib/rack/etag.rb:27:in `call'", "/usr/local/bundle/gems/rack-2.2.10/lib/rack/conditional_get.rb:27:in `call'", "/usr/local/bundle/gems/rack-2.2.10/lib/rack/head.rb:12:in `call'", "/usr/local/bundle/gems/activerecord-7.1.4.2/lib/active_record/migration.rb:655:in `call'", "/usr/local/bundle/gems/actionpack-7.1.4.2/lib/action_dispatch/middleware/callbacks.rb:29:in `block in call'", "/usr/local/bundle/gems/activesupport-7.1.4.2/lib/active_support/callbacks.rb:101:in `run_callbacks'", "/usr/local/bundle/gems/actionpack-7.1.4.2/lib/action_dispatch/middleware/callbacks.rb:28:in `call'", "/usr/local/bundle/gems/actionpack-7.1.4.2/lib/action_dispatch/middleware/executor.rb:14:in `call'", "/usr/local/bundle/gems/actionpack-7.1.4.2/lib/action_dispatch/middleware/actionable_exceptions.rb:16:in `call'", "/usr/local/bundle/gems/appsignal-4.1.2/lib/appsignal/rack/abstract_middleware.rb:66:in `call'", "/usr/local/bundle/gems/rollbar-3.6.0/lib/rollbar/middleware/rails/rollbar.rb:25:in `block in call'", "/usr/local/bundle/gems/rollbar-3.6.0/lib/rollbar.rb:145:in `scoped'", "/usr/local/bundle/gems/rollbar-3.6.0/lib/rollbar/middleware/rails/rollbar.rb:22:in `call'", "/usr/local/bundle/gems/actionpack-7.1.4.2/lib/action_dispatch/middleware/debug_exceptions.rb:29:in `call'", "/usr/local/bundle/gems/rollbar-3.6.0/lib/rollbar/middleware/rails/show_exceptions.rb:27:in `call_with_rollbar'", "/usr/local/bundle/gems/actionpack-7.1.4.2/lib/action_dispatch/middleware/show_exceptions.rb:31:in `call'", "/usr/local/bundle/gems/actionpack-7.1.4.2/lib/action_dispatch/middleware/remote_ip.rb:92:in `call'", "/usr/local/bundle/gems/request_store-1.7.0/lib/request_store/middleware.rb:19:in `call'", "/usr/local/bundle/gems/actionpack-7.1.4.2/lib/action_dispatch/middleware/request_id.rb:28:in `call'", "/usr/local/bundle/gems/rack-2.2.10/lib/rack/runtime.rb:22:in `call'", "/usr/local/bundle/gems/activesupport-7.1.4.2/lib/active_support/cache/strategy/local_cache_middleware.rb:29:in `call'", "/usr/local/bundle/gems/actionpack-7.1.4.2/lib/action_dispatch/middleware/executor.rb:14:in `call'", "/usr/local/bundle/gems/actionpack-7.1.4.2/lib/action_dispatch/middleware/static.rb:25:in `call'", "/usr/local/bundle/gems/rack-2.2.10/lib/rack/sendfile.rb:110:in `call'", "/usr/local/bundle/gems/actionpack-7.1.4.2/lib/action_dispatch/middleware/host_authorization.rb:141:in `call'", "/usr/local/bundle/gems/rack-2.2.10/lib/rack/events.rb:112:in `call'", "/usr/local/bundle/gems/rack-cors-2.0.2/lib/rack/cors.rb:102:in `call'", "/usr/local/bundle/gems/railties-7.1.4.2/lib/rails/engine.rb:536:in `call'", "/usr/local/bundle/gems/protocol-rack-0.10.1/lib/protocol/rack/adapter/rack2.rb:79:in `call'", "/usr/local/bundle/gems/protocol-http-0.42.0/lib/protocol/http/middleware.rb:43:in `call'", "/usr/local/bundle/gems/protocol-rack-0.10.1/lib/protocol/rack/rewindable.rb:58:in `call'", "/usr/local/bundle/gems/protocol-http-0.42.0/lib/protocol/http/middleware.rb:43:in `call'", "/usr/local/bundle/gems/protocol-http-0.42.0/lib/protocol/http/content_encoding.rb:29:in `call'", "/usr/local/bundle/gems/protocol-http-0.42.0/lib/protocol/http/middleware.rb:43:in `call'", "/usr/local/bundle/gems/async-http-0.82.2/lib/async/http/server.rb:61:in `block in accept'", "/usr/local/bundle/gems/async-http-0.82.2/lib/async/http/protocol/http1/server.rb:71:in `each'", "/usr/local/bundle/gems/async-http-0.82.2/lib/async/http/server.rb:50:in `accept'", "/usr/local/bundle/gems/io-endpoint-0.14.0/lib/io/endpoint/wrapper.rb:182:in `block (2 levels) in accept'", "/usr/local/bundle/gems/async-2.17.0/lib/async/task.rb:197:in `block in run'", "/usr/local/bundle/gems/async-2.17.0/lib/async/task.rb:422:in `block in schedule'"]
```

**Comment by ItaloCobains** [comment]
I have interest to solve this problem may with a `PR` but I'm newbie in this ecosystem. So I'll investigate more.
